# Generated by Django 5.2.4 on 2025-07-13 19:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='chat_media/')),
                ('monthly_income', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tc', models.BooleanField()),
                ('occupation', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
