# Generated by Django 5.2.4 on 2025-08-06 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0002_alter_budget_month_alter_income_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('user', 'month', 'year')},
        ),
    ]
