# Generated by Django 5.2.4 on 2025-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0003_alter_income_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('housing', 'Housing'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('debt-payment', 'Debt-Payment'), ('clothing', 'Clothing'), ('chilcare', 'Childcare'), ('entertainment', 'Entertainment'), ('health-care', 'Health-care'), ('gifts', 'Gifts'), ('rent', 'Rent'), ('subcription', 'Subcription'), ('food', 'Food'), ('gas', 'Gas'), ('emi', 'EMI'), ('fd', 'FD')], max_length=100),
        ),
    ]
