# Generated by Django 5.2.4 on 2025-08-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
