# Generated by Django 5.2.4 on 2025-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0005_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'upi'), ('Card', 'card'), ('Cash', 'cash')], max_length=100, null=True),
        ),
    ]
