# Generated by Django 5.2.4 on 2026-03-09 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0009_fd_recurringexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('user', 'month', 'year', 'source')},
        ),
    ]
