# Generated by Django 5.2.4 on 2026-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_management', '0010_alter_income_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=120),
        ),
    ]
